### ISSUE TITLE
toolbar component property

### ISSUE THREAD

**Issue by norbin** [Haixing-Hu/vue-html-editor#2]
I am not able to use toolbar property:
`<vue-html-editor model="{{@ body}}" toolbar="[font, [bold, italic, underline]]"></vue-html-editor>`

If I give any value to tolbar , all the available sommernote buttons appear in the view.

**Comment by marciaga** [comment]
@norbin try passing the prop as follows:

```
:toolbar=[['insert',['link']]]
```

**Comment by norbin** [comment]
Sorry for that, I had some strange behaviour with browserify, can not reproduce. @marciaga Thanks for help
