### ISSUE TITLE
 Module not found: Error: Cannot resolve module 'vue-html-editor'

### ISSUE THREAD

**Issue by NovaMindLab** [Haixing-Hu/vue-html-editor#8]
import vueeditor from 'vue-html-editor' , components: {check , mlist , loading , vueeditor} , npm install vue-html-editor

But the error : Module not found: Error: Cannot resolve module 'vue-html-editor'

**Comment by maciao** [comment]
we face the same problem, try to do the following:

`import VueEditor from 'path/to/node_modules/vue-html-editor/src/vue-html-editor'`

DONE

**Comment by JoshZA** [comment]
:+1: same issue

**Comment by Haixing-Hu** [comment]
Fixed the package.json
