### ISSUE TITLE
$(...).summernote is not a function

### ISSUE THREAD

**Issue by markeilander** [Haixing-Hu/vue-html-editor#9]
Hi there,

I use vuejs-webpack-template with your package but can't seem to get it to work....

The message i get: $(...).summernote is not a function

Any ideas?

**Comment by Jamiek94** [comment]
You have to include summernote yourself.

Get the css, fonts and javascript from: https://github.com/summernote/summernote

**Comment by Haixing-Hu** [comment]
@Jamiek94 is right. Please refer to the demo page for details.
